### ISSUE TITLE
Specify AWS Region

### ISSUE THREAD

**Issue by marcgascon** [justindowning/puppet-awscli#18]
Hi,

Appart from specifying the credentials I want to specify the region name to my ~/.aws/credentials file. Because if you give a role to an ec2 instance and then you install aws-cli with your module just including it by puppet in a node you don't need any credentials, you only need the region to work and I can't find where to specify it.

**Comment by marcgascon** [comment]
Sorry for the issue it's based on the forge of puppetlabs last version. I've just: puppet module install jdowning-awscli and 1.2.0 doesn't have support for region.

When are you going to do the next release?

Sorry for the wrong report!

**Comment by justindowning** [comment]
Sorry it took me so long to release here, but this is available in [`1.3.0`](https://forge.puppetlabs.com/jdowning/awscli/readme) now. Thanks for your patience!
