### ISSUE TITLE
Suggestion: assume python is installed

### ISSUE THREAD

**Issue by ayashjorden** [justindowning/puppet-awscli#20]
Hi,
I've tried to use this module and it conflicted when tried to install python-* packages with another module(puppet-circus).

'puppet-circus' module assumes that python/pip/virtualenv are already installed and only installs circus related stuff.

Option 1, Specify 'install_python' Boolean parameter to control python installation.
Option 2, Similarly to puppet-circus, remove any python installation related code and inform the user that Python/Pip/other should be available on the host

Thank you,
Yarden

**Comment by justindowning** [comment]
I think we could do this with a `2.0` release. There are some other 'breaking changes' suggestions we could do here to modernize this module. Feel free to PR if you have an idea worked up!
