### ISSUE TITLE
Forge Release?

### ISSUE THREAD

**Issue by bflad** [justindowning/puppet-awscli#21]
Hi there! Could you please release the current version of master to the Puppet forge? There's some goodies (including IAM role support) we're using from a few months back that isn't available in 1.2.0. Thanks!

https://github.com/justindowning/puppet-awscli/compare/1.2.0...master

**Comment by justindowning** [comment]
Sorry it took me so long to release here, but [`1.3.0`](https://forge.puppetlabs.com/jdowning/awscli/readme) is available now. Thanks for your patience!
