### ISSUE TITLE
Inability to define the same profile for multiple users

### ISSUE THREAD

**Issue by mvolhontseff** [justindowning/puppet-awscli#22]
Because the $title of a resource is used to define a profile name within .aws/credentials, you cannot create the same profile for multiple users; i.e. 'default'.  If you attempt to do this, a puppet run will result in duplicate declaration errors.

Resource declarations can be used multiple times in puppet, as opposed to classes (which is one of the main things that differentiate them).  This is useful when you want to create multiple files, multiple vhosts, multiple aws creds:

Example:
foo::bar { ‘title’: }
foo::bar { ‘title2’: }
foo::bar { ‘title3’: }

The restriction here is that the resource title must be unique, otherwise you trigger a duplicate declaration error.

Because 'title' is used as a variable within an ERB template for profile creation (i.e., title3 “becomes” the profile name), this approach prohibits you from defining the same profile for different users.  As we know, it is very practical to use ‘default’ for different users, as that is what the AWS SDK will use, by default.

The solution is to move the profile name out of the title into a param, and make the corresponding adjustments to variable assignments and .erb template.  Thus, you can adhere to the “unique title” requirement of puppet, avoid dup declarations, and still support multiple user accounts using the same profile name, i.e., “default”.  Example:

define aws_creds::profile(
  $user                  = 'root',
  $aws_profile           = 'default',
  $aws_access_key_id     = undef,
  $aws_secret_access_key = undef,
) {
  if $aws_access_key_id == undef {
    fail ('no aws_access_key_id provided')
  }

...
...
  concat::fragment{ "${user}${aws_profile}":
    target  => "${homedir}/.aws/credentials",
    content => template('aws_creds/credentials_concat.erb')
  }
}

concat.erb:
[<%=@aws_profile%>]
aws_access_key_id=<%=@aws_access_key_id%>
aws_secret_access_key=<%=@aws_secret_access_key%>

**Comment by justindowning** [comment]
I'm not sure I understand the use case here. Why would the same users on a host use the same AWS credentials (or other parameter in the `.aws/credentials` file)?

**Comment by jgnagy** [comment]
if, on a single system, multiple users need an AWS cli profile called "default" (since most tools / libraries make it difficult to use named profiles), this isn't possible to achieve given your use of $title. I agree that the solution should be to make an `aws_profile` param if you want something other than "default", and the actual $title can be ignored other than puppet's internal use.

**Comment by mvolhontseff** [comment]
@justindowning 
The use case isn't the **same** users on the same system, it is  **different** users on the same system, using the same profile name within their credentials/config files (i.e., 'default').  This is very useful when you deploy different IAM creds for different users on the same system, depending on the AWS perms you want to authorize for each user (super-users vs S3 bucket manager).  The way it is handled currently, you need to define a different resource title for each user, which would translate to different profile names.  This would require unpleasant adjustments on the cli/sdk.  Example:

User A creds file:
[default]
aws_access_key_id=AKIAIOSFODNN7EXAMPLE 
aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

User B creds file:
[default2]  <==== necessary to use "default2" in the resource declaration to avoid dup declaration
aws_access_key_id=AKIAI44QH8DHBEXAMPLE  
aws_secret_access_key=je7MtGbClwBF/2Zp9Utk/h3yCo8nvbEXAMPLEKEY

User B must then do:
aws ec2 describe-instances --profile default2

Parameterizing the profile name allows both users to use default, requiring no adjustments on the CLI or within an SDK (boto, etc).

jgnagy's commit looks good; in fact he simplified my approach by retaining the use of $title within the concat::fragment statements (which will always be unique).

**Comment by mvolhontseff** [comment]
FYI implementing the code changes per @jgnagy or my advice will certainly be a backwards compatibility breaking release.

**Comment by jgnagy** [comment]
My PR includes an update to the README that briefly describes the change as breaking. It wouldn't hurt to accentuate that a bit more if the PR is accepted, perhaps with a minor (or even major) version bump.

**Comment by jccl** [comment]
I created https://github.com/justindowning/puppet-awscli/issues/24, but realised the issue probably  makes more sense to be fixed as part of this. Please note the naming format of a named profile is different between `~/.aws/credentials` and `~/.aws/config`.

**Comment by mvolhontseff** [comment]
@jccl I modified the .erb template to incorporate your changes.  Good catch, thanks.  Tested as working in my env.

**Comment by jgnagy** [comment]
@jccl and @mvolhontseff, agreed, this is a good catch, and I'm happy to integrate a check (and appropriate logic) for this here if we all agree it makes sense to do so.

**Comment by mvolhontseff** [comment]
@jgnagy - updated config_concat.erb and submitted a pull request

**Comment by jgnagy** [comment]
Merged, and I updated the README. We'll see if all the tests still pass, then maybe @justindowning can merge this in for us.

**Comment by justindowning** [comment]
Merged #23 🎉
