### ISSUE TITLE
Generated config for named profiles are missing 'profile' keyword

### ISSUE THREAD

**Issue by jccl** [justindowning/puppet-awscli#24]
Based on http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-multiple-profiles:

> The AWS credentials file uses a different naming format than the CLI config file for named profiles. Do not include the 'profile ' prefix when configuring a named profile in the AWS credentials file.

That means, if you have a profile `[user2]` in `~/.aws/credentials`, then the corresponding profile in `~/.aws/config` should be `[profile user2]`. Currently, the generated `~/.aws/config` is missing the `profile` for profile names.

**Comment by justindowning** [comment]
This is fixed in #23.
