### ISSUE TITLE
"Could not locate the pip command. at 45:" @CentOS 6.7

### ISSUE THREAD

**Issue by nomoresecrets** [justindowning/puppet-awscli#31]
looks like something is wrong here?!

`Error: Could not set 'present' on ensure: Could not locate the pip command. at 45:/etc/puppet/modules/awscli/manifests/init.pp
Error: Could not set 'present' on ensure: Could not locate the pip command. at 45:/etc/puppet/modules/awscli/manifests/init.pp
Wrapped exception:
Could not locate the pip command.
Error: /Stage[main]/Awscli/Package[awscli]/ensure: change from absent to present failed: Could not set 'present' on ensure: Could not locate the pip command. at 45:/etc/puppet/modules/awscli/manifests/init.pp`

Thanks for your help.

**Comment by justindowning** [comment]
Seems like your host is missing `python-pip`.

**Comment by nomoresecrets** [comment]
unfortunately it is installed

`Installed Packages
Name        : python-pip
Arch        : noarch
Version     : 7.1.0
Release     : 1.el6
Size        : 6.6 M
Repo        : installed
From repo   : epel`

still the awscli-module cannot find the pip command.

Any suggestions?

**Comment by justindowning** [comment]
Maybe `pip` is not in your `$PATH`?

**Comment by nomoresecrets** [comment]
pip command is located under /usr/bin/pip

So, it is available via $PATH

**Comment by nomoresecrets** [comment]
fixed it by adding a symlink

`  file { '/usr/bin/pip-python':
    ensure => 'link',
    target => '/usr/bin/pip',
  }

  class { 'awscli':
    require => File[ '/usr/bin/pip-python' ],
  }`
