### ISSUE TITLE
https now required 

### ISSUE THREAD

**Issue by michaelnlindsay** [justindowning/puppet-awscli#34]
For the last couple of weeks, this module has been throwing the following error:

==> default: Error: Could not get latest version: HTTP-Error: 403 Must access using HTTPS instead of HTTP
==> default: Error: /Stage[main]/Awscli/Package[awscli]/ensure: change from 1.10.38 to latest failed: Could not get latest version: HTTP-Error: 403 Must access using HTTPS instead of HTTP

I'm calling it like so:

  class { 'awscli':
    version   => 'latest',
  }

And I can't find where to configure this.  Any suggestions?

**Comment by michaelnlindsay** [comment]
I'm running Ubuntu 14.04.4

**Comment by fordodone** [comment]
also, hit this issue this morning

**Comment by fordodone** [comment]
I ran `pip uninstall awscli` followed by `puppet agent -t` and it resolved the problem

**Comment by fordodone** [comment]
https://tickets.puppetlabs.com/browse/PUP-6413

**Comment by justindowning** [comment]
Thanks for the link @fordodone. @michaelnlindsay it appears the bug is with the pip provider in Puppet. I suggest you remove the `version` param from your class instance or set a specific version number if the default 'present' is not suitable.
