### ISSUE TITLE
Need install_options for pip install for awscli so we can set the proxy variable

### ISSUE THREAD

**Issue by adamjk-dev** [justindowning/puppet-awscli#36]
Currently, there is no way to pass a proxy variable to the package command to install awscli via pip.

Something like this:
```
package { 'awscli':
  ensure   => $version,
  provider => 'pip',
  install_options => '--proxy $proxy'
  require  => [
    Package['python-pip'],  
    Class['awscli::deps'],
  ],
 }
```

And, should likely make $proxy a class parameter to the init class, and perhaps a default in params.pp. Or, perhaps switch over the presence of a $proxy variable and have two resources for package (one that uses the proxy, one that doesn't).

**Comment by adamjk-dev** [comment]
Side note: I am not even sure that install_options work for the pip provider in many Puppet versions: https://tickets.puppetlabs.com/browse/PUP-1071

I had to create a file in /etc/pip.conf and set the proxy there in the [global] section.

**Comment by justindowning** [comment]
You are good at finding these corner cases @adamjk-dev! Again, thanks for documenting the problem and solution for future users who might stumble upon this. If you see improvements upstream in the way Puppet's package provider handles install_options, please open another issue to revisit. 💚
