### ISSUE TITLE
pip command on centOS 7 requires /usr/bin/pip-python which is not installed by easy_install

### ISSUE THREAD

**Issue by alexholliz** [justindowning/puppet-awscli#37]
I needed to create a symlink for pip-python in /usr/bin in order for the puppet module to install awscli. 
For (at least) centOS 7, /usr/bin/pip is the pip binary. I had to add a link in the puppet-awscli module in order to get it to work.

**Comment by justindowning** [comment]
As noted in #35, this is a bug with Puppet. I would setup a resource that is applied _before_ you call you `awscli` class instance:
```
  # Workaround for PUP-4997/3829
  file { '/usr/bin/pip-python':
    ensure => 'link',
    target => '/usr/bin/pip',
  }```
