### ISSUE TITLE
Issues with puppetlabs-concat versions?

### ISSUE THREAD

**Issue by MacLeodMike** [justindowning/puppet-awscli#42]
> Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, 10 is not a string.  It looks to be a Fixnum at /etc/puppetlabs/code/environments/production/modules/concat/manifests/fragment.pp:43:3  at /etc/puppetlabs/code/environments/production/modules/awscli/manifests/profile.pp:101 on node testhost

I'm getting the above error when trying to use create_resources with awscli::profile. Per https://github.com/justindowning/puppet-awscli/issues/40 locking puppetlabs-concat to version '1.2.0' appears to resolve the issue.

I can see that the metadata.json in puppetlabs-concat says it's version 2.2.0, but the forge still lists 1.1.0 as the latest version. And locking the version to 1.2.0 solves the problem.

I'm unfamiliar enough with puppet that I'm hoping someone else can solve that.

**Comment by vrowley** [comment]
I don't know how much this will help, but I had this problem yesterday and this morning, after we updated all our external packages, the error went away and it's using concat v 1.2.5
