### ISSUE TITLE
puppet 4 support

### ISSUE THREAD

**Issue by mleklund** [justindowning/puppet-awscli#48]
Is puppet 4 support forthcoming?

**Comment by justindowning** [comment]
I'm not familiar with the changes brought about in Puppet 4. Can you elaborate on what needs to change with this module to make it compatible with Puppet 4?

**Comment by mleklund** [comment]
At the very least you need to change your requirements in metadata.json.  

` "requirements": [
    { "name": "pe", "version_requirement": "3.x" },
    { "name": "puppet", "version_requirement": "3.x" }
  ]`

to something like:
`"requirements": [
    {
      "name": "puppet",
      "version_requirement": ">= 3 < 5.0.0"
    }`

I have not run puppet tests against the module because it says in metadata.json it does not support it.

**Comment by justindowning** [comment]
@mleklund This should be resolved in `master` now. Could you try the latest changes and let me know if it works for you?

**Comment by mleklund** [comment]
looks to be working.
