### ISSUE TITLE
AmazonLinux Support

### ISSUE THREAD

**Issue by itsSaad** [justindowning/puppet-awscli#52]
Can we please add support for Amazon Linux. I know it comes pre-installed with AWS Cli. but for version management and etc it might be helpful.

**Comment by justindowning** [comment]
It should just work since we [support RedHat](https://github.com/justindowning/puppet-awscli/blob/master/metadata.json#L30-L33). Have you tried with Amazon Linux?

**Comment by itsSaad** [comment]
Yes i have tried on AmazonLinux specifically and it ran into an error. So i had to add an if statement for AmazonLinux.

**Comment by justindowning** [comment]
Okay. Do you have an example of what changes you had to make in order for it to work on Amazon LInux? Would you like to submit a PR?

**Comment by justindowning** [comment]
I wrote up a quick example on getting this to work on Amazon Linux in a9431e7.
