### ISSUE TITLE
Default file mode is world-readable

### ISSUE THREAD

**Issue by swhisnant** [justindowning/puppet-awscli#53]
Precondition:

- VM with puppet-server-3.3.1 installed
  - `/etc/puppet/manifests/nodes.pp` containing an empty node definition for the agent VM
  - `/etc/puppet/manifests/site.pp` containing a directive to import the nodes file
- VM with Puppet agent installed and provisioned to communicate with the master

Steps to reproduce:

1. On the Puppet master, in the empty node definition, add a block that will invoke `awscli::profile` with an AWS access key ID, secret access key, and region:
```
  awscli::profile { 'AWSProfile':
    aws_access_key_id => '[redacted]',
    aws_secret_access_key => '[redacted]',
    aws_region => 'us-east-1',
  }
```
2. Update (apply) the catalog with the new changes
3. In the Puppet agent VM as a non-root user, apply the update:
```
sudo puppet agent --test --no-daemonize --server [host name of master VM]
```
4. In the Puppet agent VM as a non-root user, explore the contents of the newly-created .aws metadata folder in the root user's home:
```
sudo ls -al /root/.aws
```

Expected:
The mode of the .aws folder and its contents should, by default, disallow global read access. The official AWS client creates the .aws folder with a mode of 0700 and the files within with a mode of 0600.

Actual:
The mode of the .aws folder and contents are 0755 and 0644 respectively, given the default umask is 0002.

**Comment by justindowning** [comment]
Thanks for the detailed bug report! This fixed in `master` now.
