### ISSUE TITLE
requires PIP but doesn't install it

### ISSUE THREAD

**Issue by cdenneen** [justindowning/puppet-awscli#6]
Error: Could not set 'present' on ensure: Could not locate the pip command. at 33:/tmp/modules/awscli/manifests/init.pp
Error: Could not set 'present' on ensure: Could not locate the pip command. at 33:/tmp/modules/awscli/manifests/init.pp

**Comment by justindowning** [comment]
What `$::osfamily` are you using? If `pip` is not installed or managed in the node catalog, it will install it on debian, redhat, or osx:  https://github.com/justindowning/puppet-awscli/tree/master/manifests/deps.
