### ISSUE TITLE
build is broken

### ISSUE THREAD

**Issue by paschdan** [justindowning/puppet-awscli#8]
The Build is broken, because puppetlabs-concat got a new module dependency with 1.2.1

To fix the build you can
* pin puppetlabs/concat to 1.2.0
* add electrical/file_concat to fixtures

I have both solutions already done, tell me which one you like more:

1: https://github.com/justindowning/puppet-awscli/compare/master...asgoodasnu:fix-dependencies?expand=1

2: https://github.com/justindowning/puppet-awscli/compare/master...asgoodasnu:add-file-concat?expand=1

**Comment by justindowning** [comment]
Let's go with the second choice of just adding to the fixtures. Thanks!
